# Global settings applied to the whole site
[build]
  base = "client/"        # Base directory for the project
  publish = "client/build" # Directory to publish
  command = "npm run build" # Command to build your site

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensure that even if there’s a file at that path, the redirect is still performed

# Headers
[[headers]]
  # Define which paths this rule applies to
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
